name: Report a problem
description: If you have an issue with Auto Dark Mode
labels: ['needs triage']
body:
  - type: markdown
    attributes:
      value: |
        # Please check the list of known issues first
        You can find them here: [Known issues and limitations](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Known-limitations)
        If your issue is listed there, we are aware and you don't need to file a report.
      
        # Please update to the latest beta first
        Go to settings and select the "Beta" update channel.
        Click "Check for Updates" and ensure the info message reads "No new updates available".
        If you live in China, the updater will not work because raw.githubusercontent is blocked. Instead, please use a VPN or go to the [Beta repository](https://github.com/AutoDarkMode/AutoDarkModeVersion/releases) and update manually.
        
        # Old Auto Dark Mode Versions
        Please don't file issue reports if you are on versions 10.3 or earlier.
        We do not provide support for older versions of the software.
        
        Additional information:
        - Auto Dark Mode 10.1 is incompatible with Windows 11 22H2.
        - Auto Dark Mode 10.2 is partly incompatible with Windows 11 22H2.
        - Auto Dark Mode 10.3 support ended on the 10th of September, 2023.
        
        # Issue Report
        
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a concise description of what steps/clicks/modifications you made from the beginning, until the issue occurs
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description:  Describe what you see. How does that differ from what you expect?
      placeholder: |
        ADM should do this
        ADM should do that
    validations:
      required: false

  - type: textarea
    id: logdata
    attributes:
      label: Log Data
      description:  |
        Attach the service.log file
        Attach the config.yaml file
        They can be found in %AppData%\AutoDarkMode
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Commit Hash, Version and Windows Build
      description: Go to the About Page and copy the version info
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Videos
      description: If applicable, please provide screenshots or videos depicting the problem.
    validations:
      required: false
